name: Python Tests

on:
  push:
    paths:
      - "**.py"
      - "tests/**"
  pull_request:
    paths:
      - "**.py"
      - "tests/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Set up CUDA
        uses: NVIDIA/cuda-toolkit
        with:
          cuda: "12.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pytest torch
      - name: Check CUDA availability
        run: python -c "import torch; assert torch.cuda.is_available(), 'CUDA is not available'"
      - name: Run tests
        run: python -m pytest tests/ --maxfail=1 -v -s
